### ISSUE TITLE
Enhancement proposal: pyzabbix.client with 

### ISSUE THREAD

**Issue by P6rguVyrst** [lukecyca/pyzabbix#100]
Hey!

Thank you for the pyzabbix library, It's well designed, simple to interact with and effective. I use it a lot to automate stuff and add business value to Zabbix.

I have however felt, that it would be nice if there were better defined and documented methods inside the library as well. I know Zabbix API documentation is really, really good, but it might be nice if there was an option to use Zabbix Python client that would validate user input before turning to make the API call as well.

I am not sure if it's a good idea, but I tried implementing some extra functionality to pyzabbix, while leaving the original behavior intact: https://github.com/P6rguVyrst/pyzabbix/commit/a7d4e85b2c1732dc798463bd06fe8f91716f13f2

The point is to add pyzabbix.client library with enhanced functionality to pyzabbix, which has served me well so far. There's just some functionality which I use a lot in different applications that might make everyone's life easier.

I think it might be even possible to implement this behavior as completely separate pypi package if we were to use same pyzabbix namespace - would need to test that.

If you think this is a bad idea, I'll think it over if it's worth to continue implementing this kind of behavior.

Regards,
Toomas

**Comment by lukecyca** [comment]
Thanks for you kind words and interest, @P6rguVyrst!

I would also like to get @neothematrix's opinion on this as well, as I'm not terribly involved with this project anymore.

I am skeptical because I think that going down the road of codifying the entire API in python creates duplication that is difficult to maintain. It will inevitably fall out of sync with future Zabbix versions and be outdated or incomplete (or at least appear that way).

I would also urge idiomatic python in your branch. Avoid using old-style classes, `locals()`, etc.

**Comment by P6rguVyrst** [comment]
Thank you for your feedback! 

It's easy to get carried away writing new features. Really the host creation is the most annoying part of using the API client because of the plethora of options. 

Otherwise, I think I have to agree. Since the API is so well documented, adding extra documentation and describing parameters here would probably be an unnecessary maintenance headache.

Learning Python organically is a long and painful road full of headache - thank you for the tips.

Toomas

**Comment by neothematrix** [comment]
hi! 
sorry for the very late reply, my opinion matches Luke's one, I think this library should stay as much as possible simple and generic so that it will "always work (tm)" no matter how Zabbix decides to improve/remove/add methods and parameters.
Probably the best approach for what you'd like to achieve is another "higher level" library that inherits (if possible) the base code from pyzabbix?

**Comment by neothematrix** [comment]
thanks for the input @P6rguVyrst, I'm closing this now
