### ISSUE TITLE
Getting Multiple Values Wont Work

### ISSUE THREAD

**Issue by gcavalcante8808** [lukecyca/pyzabbix#56]
Hello,

I'm trying to get some history values, but I cant get values from more than one item id in the same request. In the zabbix api documentation of the history.get we have the following info:

itemids 	string/array 	Return only history from the given items. 

But with the pyzabbix, when I try to get more than one itemid history value, i just get the LAST value provided in the itemsids list.

Example:
zapi.history.get(hostids=['13088'], itemids=['146503', '14504'], limit=1)

Result:
[{'clock': '1428588104', 'itemid': '146504', 'ns': '701674174', 'value': '1'}]

Is that behaviour ok?

**Comment by neothematrix** [comment]
hello,
that's actually a consequence of using the "limit" parameter, the limit is applied at the end of the query, and it's something managed by Zabbix API, not by pyzabbix implementation, in your case, limit=1 means to print out just one element of the json output, in case you expect to have two elements, you should at least, use limit=2.
Plus you have another issue here, since the limit is applied only on the output, without sorting, you can't be sure the first two element of the output are coming from two different itemid, it could be that both of the two elements come from the same itemid, actually they always are, unless you specify the sortfield, which by default is by "itemid", you should use "clock".
Another option, is not use the "limit" parameter, you'll notice that the output contains data from both the requested itemids.
So here an example that would work for your api query:

```python
zapi.history.get(hostids=['13088'], itemids=['146503', '14504'], limit=2, sortfield="clock")
```

I hope this helped, it's definitely not a pyzabbix issue, so I'm closing the ticket, feel free to comment or reopen if you think there are other issues I didn't see.
