### ISSUE TITLE
Getting SSL error even with `zapi.session.verify=False`

### ISSUE THREAD

**Issue by whoisearth** [lukecyca/pyzabbix#80]
I get the following traceback when trying to simply connect to our zabbix instances telling the session to verify=False.

If I try directly with requests (ie. no session) I have no issue.

This works:

`r = requests.get('https://zabbix.server.com', verify=False, auth=('username', 'password'))`

But if I remove `verify=False` I get the same error as below which is making me think the `verify=False` is not passing through the session for some reason?

Trying sessions natively through `requests` I also have no issue.  This below is clean:

```
import requests

s = requests.Session()
s.auth=('username', 'password')
s.verify=False
r = s.get('https://zabbix.server.com/zabbix/api_jsonrpc.php')
```

The example I'm trying using pyzabbix that is failing is any of the samples on your readme.

```
Traceback (most recent call last):
  File "C:/projects/zabbix/scripts/query_api.py", line 31, in <module>
    zapi.login('svc_zabbix_api')
  File "C:\Python27\lib\site-packages\pyzabbix\__init__.py", line 70, in login
    self.auth = self.user.login(user=user, password=password)
  File "C:\Python27\lib\site-packages\pyzabbix\__init__.py", line 157, in fn
    args or kwargs
  File "C:\Python27\lib\site-packages\pyzabbix\__init__.py", line 103, in do_request
    timeout=self.timeout
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by neothematrix** [comment]
hello,
did you read the "Readme.markdown" description of the package? You can find an example on how to pass the verify=False properties:

# Disable SSL certificate verification
zapi.session.verify = False

feel free to reopen the issue if this doesn't solve your issue.

**Comment by whoisearth** [comment]
ok that makes  sense.  Problem was the difference between what is expected with just doing `zapi.` and doing `zapi.session.`

Is there a reason why one is set for `zapi.session.auth` and the other is `zapi.login`?  

Not sure why but I have to disable the verify in the session but I then have to login without a session.

ie. this is how I have to connect:

```
from pyzabbix import ZabbixAPI, ZabbixAPIException

# The hostname at which the Zabbix web interface is available
ZABBIX_SERVER = 'https://zabbix.domain.com/zabbix'

zapi = ZabbixAPI(ZABBIX_SERVER)

# Disable SSL certificate verification
zapi.session.verify = False

zapi.login('zabbix', 'pass')
for h in zapi.host.get():
    print h['host']
```

passing the authorization via `zapi.session.auth = ('zabbix', 'pass')` does not work and gives me an invalid credentials.

**Comment by neothematrix** [comment]
Mmm you are confusing things a little bit:

zapi.session allows you to change parameter for the Session object linked
to the ZabbixAPI object, so you are actually "talking" to the Session
object directly.
zapi.login allows you to talk to the ZabbixAPI object.

To answer your question (and again, this is explained on the readme),
zapi.session.auth needs to be used only if you have configured Zabbix with
"http authentication" instead of the default of "internal authentication"
or "ldap authentication", otherwise you have to use the zapi.login method.

**Comment by mchingotto** [comment]
Hello,

   I am having the same issue.
  requests.exceptions.SSLError: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /zabbix/api_jsonrpc.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))

Using:
   zapi.session.verify = False

Help will be appreciated.
Thanks,
M

**Comment by devsango** [comment]
I am having the same issue with SSLEror : (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)), 
I can't get pass the ZabbixAPI("url") function: 

     **from pyzabbix import ZabbixAPI**
     **zapi = ZabbixAPI("'https://zabbix.domain.com/zabbix'")**

Is there a way to disable ssl verification before the zabi session?
I am working on a project that relies solely on using the ZabbixAPI object.

Thank you for any help I can get.

**Comment by mchingotto** [comment]
Hello,

   I had same problem.

   Maybe you could use requests instead of the ZabbixAPI. Maybe it helps. It works without any problem.

   I know it sounds a not related issue, but some installation of zabbix does not have the /zabbix/ part in the URL. If I were you I would try also taking this out.

Cheers,

**Comment by linceaerian** [comment]
Hello @devsango (and other who look at the issue :))

You can directly add

```
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

The message is from urllib3.

Ex of working code with un-certified cert (unrecognized CA).

![image](https://user-images.githubusercontent.com/1318470/130639677-0aafc8f6-5798-4e16-ae10-f6be181f4f23.png)

**Comment by ps566730** [comment]
The urllib3 addition didn't help me on this one.  It is hitting some problem in the ZabbixAPI instantiation that generates the error, it never gets to the part where you can set zapi.session.verify=False

**Comment by linceaerian** [comment]
Yes, you can close it, it's an old one :)
