### ISSUE TITLE
item.create fails but item gets created anyway

### ISSUE THREAD

**Issue by karsou** [lukecyca/pyzabbix#94]
I am making an API call as follows:

```
zapi.do_request('item.create', {"name":item_name, "key_":key, "hostid":hostid, "type":2, "value_type":0, 'interfaceid':interfaceid, 'delay':300}) 
```
I am getting this error:
```
Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/zabbix_bridge.py", line 25, in <module>
    response = zapi.do_request('item.create', {"name":item_name, "key_":key, "hostid":hostid, "type":2, "value_type":0, 'interfaceid':interfaceid, 'delay':300})
  File "/usr/local/lib/python2.7/dist-packages/pyzabbix/api.py", line 250, in do_request
    raise ZabbixAPIException(msg, err['code'])
pyzabbix.api.ZabbixAPIException: ('Error -32602: Invalid params., Item with key "zabbix-server.version" already exists on "Zabbix server". while sending {\'params\': {\'interfaceid\': u\'1\', \'hostid\': u\'10084\', \'key_\': \'zabbix-server.version\', \'name\': \'Server.zabbix-server.version\', \'delay\': 300, \'value_type\': 0, \'type\': 2}, \'jsonrpc\': \'2.0\', \'method\': \'item.create\', \'auth\': u\'7af8c31adf45794cac6d62e443e13884\', \'id\': \'1\'}', -32602) 
```
Funny thing, the item gets created anyway.

**Comment by neothematrix** [comment]
hello, I just tried the same command and the item was created as expected, the second time I run the command, I received the same error message as expected, because the item "zabbix-server.version" already existed.
Hence my question, are you sure the item you're trying to create doesn't exist already?

Just a curiosity, why are you using the zapi.do_request call? you know you can use:
zapi.item.create('hostid': hostid, 'key_': key,....)?
nothing wrong about using do_request, but I find the latter slightly more readable.

**Comment by neothematrix** [comment]
closing, feel free to reopen if you have additional info! thanks
